version: 0.2

phases:
  install:
    commands:
      # Install dependencies needed for running tests
      - npm cache clean -f
      - npm install -g n
      - n stable
      - npm install

      # Upgrade AWS CLI to the latest version
      - pip install --upgrade awscli
  pre_build:
    commands:
      - aws cloudformation package --template template.yml --s3-bucket $S3_BUCKET --output-template template-export.yml
  build:
    commands:
      - mv buildspec.publish.yml buildspec.yml
artifacts:
  files:
    - '**/*'
  discard-paths: no